# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Yingping' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
#    pod 'GGShareKit', :git => 'git@gitlab.cngump.com:ganguo_ios/third_login_ios.git'
  # Pods for Yingping
    pod 'Bugly'

  target 'YingpingTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
